bot:
  username: your-bot-account@gmail.com # Existing account of your bot
  password: bot-password # Password of the account
  allowed: ['friend1@gmail.com', 'friend1@gmail.com'] # Authorized accounts for communication
twitter:
  consumer_key: YOUR CONSUMER KEY # Twitter consumer key
  consumer_secret: YOUR CONSUMER SECRET KEY # Twitter consumer secret key
  gateway: api.apigee.com # Twitter gateaway